import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatDate } from './utils'

// Branding Colors
const BRAND_PRIMARY = [30, 58, 138] // Slate/Indigo #1E3A8A
const BRAND_ACCENT = [37, 99, 235] // Blue #2563EB
const BRAND_GRAY = [100, 116, 139] // Slate #64748B

/**
 * Standard FluidControl Header for all PDF documents
 */
function addDocumentHeader(
  doc: jsPDF,
  title: string,
  subtitle?: string,
  metaItems?: { label: string; value: string }[]
) {
  const pageWidth = doc.internal.pageSize.getWidth()

  // Top Accent Bar
  doc.setFillColor(BRAND_ACCENT[0], BRAND_ACCENT[1], BRAND_ACCENT[2])
  doc.rect(0, 0, pageWidth, 4, 'F')

  // Company Name
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(BRAND_PRIMARY[0], BRAND_PRIMARY[1], BRAND_PRIMARY[2])
  doc.text('FLUIDCONTROL PRIVATE LIMITED', 14, 15)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(BRAND_GRAY[0], BRAND_GRAY[1], BRAND_GRAY[2])
  doc.text('Employee Training & Safety Management System', 14, 20)

  // Report Title Box
  doc.setDrawColor(226, 232, 240)
  doc.setFillColor(248, 250, 252)
  doc.roundedRect(14, 24, pageWidth - 28, 14, 2, 2, 'FD')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(15, 23, 42)
  doc.text(title.toUpperCase(), 18, 32)

  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(BRAND_GRAY[0], BRAND_GRAY[1], BRAND_GRAY[2])
    doc.text(subtitle, 18, 36)
  }

  // Metadata items row if present
  let currentY = 42
  if (metaItems && metaItems.length > 0) {
    doc.setFontSize(8.5)
    let currentX = 14
    metaItems.forEach(item => {
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(71, 85, 105)
      doc.text(`${item.label}: `, currentX, currentY)
      const labelWidth = doc.getTextWidth(`${item.label}: `)

      doc.setFont('helvetica', 'normal')
      doc.setTextColor(15, 23, 42)
      doc.text(item.value, currentX + labelWidth, currentY)
      const valWidth = doc.getTextWidth(item.value)

      currentX += labelWidth + valWidth + 12
    })
    currentY += 6
  }

  return currentY
}

/**
 * Standard FluidControl Footer with Page numbers and Signatures
 */
function addDocumentFooter(doc: jsPDF, includeSignatures = false) {
  const pageCount = (doc as unknown as { internal: { getNumberOfPages: () => number } }).internal.getNumberOfPages()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)

    // Signatures on the last page if requested
    if (includeSignatures && i === pageCount) {
      const sigY = pageHeight - 32
      doc.setDrawColor(203, 213, 225)
      doc.setLineWidth(0.5)

      // Trainer Line
      doc.line(14, sigY, 70, sigY)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100, 116, 139)
      doc.text("Trainer's Signature & Date", 14, sigY + 5)

      // HR Manager Line
      doc.line(pageWidth - 70, sigY, pageWidth - 14, sigY)
      doc.text("Authorized HR Signature", pageWidth - 70, sigY + 5)
    }

    // Bottom meta bar
    doc.setDrawColor(226, 232, 240)
    doc.line(14, pageHeight - 12, pageWidth - 14, pageHeight - 12)

    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(148, 163, 184)
    doc.text(
      `Generated by FluidControl ETMS on ${new Date().toLocaleString('en-US')}`,
      14,
      pageHeight - 7
    )
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 14,
      pageHeight - 7,
      { align: 'right' }
    )
  }
}

/**
 * Generates and downloads a Printable Attendance Sheet PDF
 */
export function exportAttendanceSheetPdf(params: {
  trainingName: string
  trainerName: string
  scheduledDate: string
  groupType: string
  employees: {
    code: string
    name: string
    department: string
    designation: string
    status: string
  }[]
}) {
  const doc = new jsPDF('portrait', 'mm', 'a4')

  const startY = addDocumentHeader(
    doc,
    'Training Attendance Sheet',
    'Official session record for compliance and verification',
    [
      { label: 'Training', value: params.trainingName },
      { label: 'Date', value: formatDate(params.scheduledDate) },
      { label: 'Trainer', value: params.trainerName },
      { label: 'Enrolled', value: `${params.employees.length} Employees` },
    ]
  )

  const tableData = params.employees.map((emp, index) => [
    index + 1,
    emp.code,
    emp.name,
    emp.department,
    emp.designation,
    emp.status.replace('_', ' ').toUpperCase(),
    '', // Empty signature box for print/signing
  ])

  autoTable(doc, {
    startY: startY + 2,
    head: [['#', 'Emp Code', 'Employee Name', 'Department', 'Designation', 'Attendance', 'Signature']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 41, 59],
      cellPadding: 3,
    },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      1: { cellWidth: 20, fontStyle: 'bold' },
      2: { cellWidth: 40 },
      3: { cellWidth: 32 },
      4: { cellWidth: 32 },
      5: { cellWidth: 24, halign: 'center' },
      6: { cellWidth: 30 }, // Signature box
    },
    didDrawCell: (data) => {
      // Style attendance text colors
      if (data.section === 'body' && data.column.index === 5) {
        const text = String(data.cell.raw)
        if (text === 'PRESENT') {
          doc.setTextColor(16, 185, 129)
        } else if (text === 'ABSENT') {
          doc.setTextColor(239, 68, 68)
        } else {
          doc.setTextColor(245, 158, 11)
        }
      }
    },
    margin: { bottom: 40 },
  })

  addDocumentFooter(doc, true)
  const cleanName = params.trainingName.replace(/[^a-zA-Z0-9_-]/g, '_')
  doc.save(`FluidControl_Attendance_${cleanName}_${params.scheduledDate}.pdf`)
}

/**
 * Generates and downloads an HR Training Compliance & Analytics Report PDF
 */
export function exportComplianceReportPdf(params: {
  records: {
    employeeName: string
    employeeCode: string
    department: string
    trainingName: string
    scheduledDate: string
    status: string
    completedOn?: string
    dueDate?: string
  }[]
  filterSummary?: string
  counts: {
    completed: number
    pending: number
    overdue: number
  }
}) {
  const doc = new jsPDF('landscape', 'mm', 'a4')

  const total = params.records.length
  const complianceRate = total > 0 ? Math.round((params.counts.completed / total) * 100) : 0

  const startY = addDocumentHeader(
    doc,
    'Training Compliance & Audit Report',
    params.filterSummary || 'Overall company training completion and compliance log',
    [
      { label: 'Completed', value: `${params.counts.completed}` },
      { label: 'Pending', value: `${params.counts.pending}` },
      { label: 'Overdue', value: `${params.counts.overdue}` },
      { label: 'Compliance Rate', value: `${complianceRate}%` },
      { label: 'Total Records', value: `${total}` },
    ]
  )

  const tableData = params.records.map((r, idx) => [
    idx + 1,
    `${r.employeeName} (${r.employeeCode})`,
    r.department,
    r.trainingName,
    formatDate(r.scheduledDate),
    r.status.toUpperCase(),
    r.completedOn ? formatDate(r.completedOn) : '—',
    r.dueDate ? formatDate(r.dueDate) : '—',
  ])

  autoTable(doc, {
    startY: startY + 2,
    head: [['#', 'Employee', 'Department', 'Training Program', 'Date', 'Status', 'Completed On', 'Due Date']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 41, 59],
      cellPadding: 2.5,
    },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      1: { cellWidth: 50, fontStyle: 'bold' },
      2: { cellWidth: 42 },
      3: { cellWidth: 60 },
      4: { cellWidth: 26 },
      5: { cellWidth: 26, halign: 'center' },
      6: { cellWidth: 28 },
      7: { cellWidth: 28 },
    },
    didDrawCell: (data) => {
      if (data.section === 'body' && data.column.index === 5) {
        const text = String(data.cell.raw)
        if (text === 'COMPLETED') {
          doc.setTextColor(16, 185, 129)
        } else if (text === 'OVERDUE') {
          doc.setTextColor(239, 68, 68)
        } else {
          doc.setTextColor(245, 158, 11)
        }
      }
    },
    margin: { bottom: 20 },
  })

  addDocumentFooter(doc, false)
  const todayStr = new Date().toISOString().split('T')[0]
  doc.save(`FluidControl_Training_Report_${todayStr}.pdf`)
}

/**
 * Generates and downloads an Employee Training Certificate / History Report PDF
 */
export function exportEmployeeHistoryPdf(params: {
  employee: {
    name: string
    code: string
    email: string
    department: string
    designation: string
  }
  history: {
    trainingName: string
    date: string
    status: string
    completedOn?: string
  }[]
}) {
  const doc = new jsPDF('portrait', 'mm', 'a4')

  const startY = addDocumentHeader(
    doc,
    `Individual Training Record — ${params.employee.name}`,
    `Employee Code: ${params.employee.code} | Dept: ${params.employee.department} | ${params.employee.designation}`,
    [
      { label: 'Employee', value: params.employee.name },
      { label: 'Email', value: params.employee.email },
      { label: 'Trainings Completed', value: `${params.history.filter(h => h.status === 'completed').length}` },
    ]
  )

  const tableData = params.history.map((h, idx) => [
    idx + 1,
    h.trainingName,
    formatDate(h.date),
    h.status.toUpperCase(),
    h.completedOn ? formatDate(h.completedOn) : '—',
  ])

  autoTable(doc, {
    startY: startY + 2,
    head: [['#', 'Training Program', 'Scheduled Date', 'Status', 'Completed On']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8.5,
      textColor: [30, 41, 59],
      cellPadding: 3,
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 75, fontStyle: 'bold' },
      2: { cellWidth: 35 },
      3: { cellWidth: 30, halign: 'center' },
      4: { cellWidth: 35 },
    },
    margin: { bottom: 35 },
  })

  addDocumentFooter(doc, true)
  const cleanCode = params.employee.code.replace(/[^a-zA-Z0-9_-]/g, '_')
  doc.save(`FluidControl_Record_${cleanCode}.pdf`)
}

/**
 * Generates and downloads an Employee Directory Master List PDF
 */
export function exportEmployeeDirectoryPdf(params: {
  employees: {
    code: string
    name: string
    email: string
    department: string
    designation: string
    status: string
  }[]
  filterSummary?: string
}) {
  const doc = new jsPDF('landscape', 'mm', 'a4')

  const total = params.employees.length
  const activeCount = params.employees.filter(e => e.status.toLowerCase() === 'active').length

  const startY = addDocumentHeader(
    doc,
    'Employee Master Directory',
    params.filterSummary || 'FluidControl Complete Staff Directory & Department Mapping',
    [
      { label: 'Total Staff', value: `${total} Employees` },
      { label: 'Active', value: `${activeCount}` },
      { label: 'Inactive', value: `${total - activeCount}` },
    ]
  )

  const tableData = params.employees.map((emp, idx) => [
    idx + 1,
    emp.code,
    emp.name,
    emp.email,
    emp.department,
    emp.designation,
    emp.status.toUpperCase(),
  ])

  autoTable(doc, {
    startY: startY + 2,
    head: [['#', 'Emp Code', 'Full Name', 'Email Address', 'Department', 'Designation', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 58, 138],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8.5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 41, 59],
      cellPadding: 2.5,
    },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      1: { cellWidth: 24, fontStyle: 'bold' },
      2: { cellWidth: 50 },
      3: { cellWidth: 65 },
      4: { cellWidth: 42 },
      5: { cellWidth: 45 },
      6: { cellWidth: 22, halign: 'center' },
    },
    didDrawCell: (data) => {
      if (data.section === 'body' && data.column.index === 6) {
        const text = String(data.cell.raw)
        if (text === 'ACTIVE') {
          doc.setTextColor(16, 185, 129)
        } else {
          doc.setTextColor(239, 68, 68)
        }
      }
    },
    margin: { bottom: 20 },
  })

  addDocumentFooter(doc, false)
  const todayStr = new Date().toISOString().split('T')[0]
  doc.save(`FluidControl_Employees_Directory_${todayStr}.pdf`)
}
